version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: vai-pela-sombra-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vai_pela_sombra
    ports:
      - "5433:5432"  # Porta externa para evitar conflito local
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vai-pela-sombra-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"  # Acesso no navegador via localhost:8080
    depends_on:
      - postgres

volumes:
  pgdata:
