openapi: 3.0.0
info:
  title: VaiPelaSombra API
  version: 1.0.0
  description: API documentation for VaiPelaSombra Backend
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  $ref: './routes/routes.paths.yaml'
components:
  schemas:
    CreateUserInput:
      type: object
      required: [name, email, password]
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        createdAt:
          type: string
          format: date-time
        profileBio:
          type: string
        profileImage:
          type: string
          format: uri

    UpdateUserInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        createdAt:
          type: string
          format: date-time
        profileBio:
          type: string
        profileImage:
          type: string
          format: uri

    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
        profileBio:
          type: string
        profileImage:
          type: string
          format: uri

    CreateTravelPreferenceInput:
      type: object
      required: [userId, transport, accommodation, activities]
      properties:
        userId:
          type: integer
        transport:
          type: string
        accommodation:
          type: string
        activities:
          type: array
          items:
            type: string
        budget:
          type: number
        duration:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

    UpdateTravelPreferenceInput:
      type: object
      properties:
        userId:
          type: integer
        transport:
          type: string
        accommodation:
          type: string
        activities:
          type: array
          items:
            type: string
        budget:
          type: number
        duration:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

    TravelPreference:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        transport:
          type: string
        accommodation:
          type: string
        activities:
          type: array
          items:
            type: string
        budget:
          type: number
        duration:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

    CreateItineraryInput:
      type: object
      required: [title, startDate, endDate, itineraryStatus]
      properties:
        title:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        itineraryStatus:
          type: string
          enum: [PLANNING, IN_PROGRESS, COMPLETED]
        foodBudget:
          type: number
        lodgingBudget:
          type: number
        totalBudget:
          type: number
        userIds:
          type: array
          items:
            type: integer
        activityIds:
          type: array
          items:
            type: integer
        destinationIds:
          type: array
          items:
            type: integer
        transportIds:
          type: array
          items:
            type: integer
        requiredDocumentIds:
          type: array
          items:
            type: integer

    UpdateItineraryInput:
      type: object
      properties:
        title:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        itineraryStatus:
          type: string
          enum: [PLANNING, IN_PROGRESS, COMPLETED]
        foodBudget:
          type: number
        lodgingBudget:
          type: number
        totalBudget:
          type: number
        userIds:
          type: array
          items:
            type: integer
        activityIds:
          type: array
          items:
            type: integer
        destinationIds:
          type: array
          items:
            type: integer
        transportIds:
          type: array
          items:
            type: integer
        requiredDocumentIds:
          type: array
          items:
            type: integer

    Itinerary:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        itineraryStatus:
          type: string
        foodBudget:
          type: number
        lodgingBudget:
          type: number
        totalBudget:
          type: number
        userIds:
          type: array
          items:
            type: integer
        activityIds:
          type: array
          items:
            type: integer
        destinationIds:
          type: array
          items:
            type: integer
        transportIds:
          type: array
          items:
            type: integer
        requiredDocumentIds:
          type: array
          items:
            type: integer

    CreateActivityInput:
      type: object
      required: [location, title, price, startTime, endTime, itineraryId]
      properties:
        location:
          type: string
        title:
          type: string
        price:
          type: number
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        duration:
          type: string
        description:
          type: string
        itineraryId:
          type: integer

    UpdateActivityInput:
      type: object
      properties:
        location:
          type: string
        title:
          type: string
        price:
          type: number
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        duration:
          type: string
        description:
          type: string

    Activity:
      type: object
      properties:
        id:
          type: integer
        location:
          type: string
        title:
          type: string
        price:
          type: number
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        duration:
          type: string
        description:
          type: string
        itineraryId:
          type: integer

    CreateTravelInterestInput:
      type: object
      required: [label]
      properties:
        label:
          type: string

    UpdateTravelInterestInput:
      type: object
      properties:
        label:
          type: string

    TravelInterest:
      type: object
      properties:
        id:
          type: integer
        label:
          type: string

    CreateTransportInput:       
      type: object
      required:
        - tipo
        - valor
        - dataCsaida
        - dataChegada
        - duracao
      properties:
        tipo:
          type: string
        valor:
          type: number
        dataCsaida:
          type: string
          format: date-time
        dataChegada:
          type: string
          format: date-time
        duracao:
          type: string
        descricao:
          type: string

    UpdateTransportInput:
      type: object
      properties:
        tipo:
          type: string
        valor:
          type: number
        dataCsaida:
          type: string
          format: date-time
        dataChegada:
          type: string
          format: date-time
        duracao:
          type: string
        descricao:
          type: string

    Transport:
      type: object
      properties:
        idTransporte:
          type: integer
        tipo:
          type: string
        valor:
          type: number
        dataCsaida:
          type: string
          format: date-time
        dataChegada:
          type: string
          format: date-time
        duracao:
          type: string
        descricao:
          type: string
