openapi: 3.0.0
info:
  title: VaiPelaSombra API
  version: 1.0.0
  description: API documentation for VaiPelaSombra Backend
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  $ref: "./routes/users.paths.yaml"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        profileBio:
          type: string
          nullable: true
        profileImage:
          type: string
          nullable: true

    CreateUserInput:
      type: object
      required: [name, email, password]
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        profileBio:
          type: string
          nullable: true
        profileImage:
          type: string
          nullable: true

    PlanoViagem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        image:
          type: string
        date:
          type: string
          format: date-time
        daysLeft:
          type: integer
        faded:
          type: boolean
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'

# (removido para testes)
#securitySchemes:
#    bearerAuth:
#     type: http
#      scheme: bearer
#      bearerFormat: JWT  
