openapi: 3.0.0
info:
  title: VaiPelaSombra API
  version: 1.0.0
  description: API documentation for VaiPelaSombra Backend
servers:
  - url: http://localhost:3000
    description: Local server
paths:
    <<: 
      - $ref: './routes/users.paths.yaml'
      - $ref: './routes/planoViagem.paths.yaml'
components:
  schemas:
    CreateUserInput:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: "João Silva"
        email:
          type: string
          format: email
          example: "joao@email.com"
        password:
          type: string
          description: Password must be hashed before sending to the service
          example: "hashed_password"
        profileBio:
          type: string
          nullable: true
          example: "Apaixonado por viagens e aventuras."
        profileImage:
          type: string
          nullable: true
          example: "https://example.com/profile.jpg"
    PlanoViagem:
        type: object
        properties:
          id:
            type: integer
          title:
            type: string
          image:
            type: string
          date:
            type: string
            format: date-time
          daysLeft:
            type: integer
          faded:
            type: boolean
          users:
            type: array
            items:
              $ref: '#/components/schemas/User'